services:
  db:
    image: mongo:8.2.2
  client:
    image: simple-sign-in/client:latest
    build:
      dockerfile: client.dockerfile
    env_file: .env
    ports:
      - 5173:5173
  server:
    image: simple-sign-in/server:latest
    build:
      dockerfile: server.dockerfile
    env_file: .env
    ports:
      - 4000:4000
